# This is a basic workflow to help you get started with Actions

name: Grab Discount Rates

# Controls when the action will run. 
on:
  # Triggers the workflow "At minute 0 past hour 8, 10, 12, and 14 on every day-of-week from Monday through Friday."
  schedule:
    - cron: '0 8,10,12,14 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  zinsgrabber:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Grab Discount Rates
        run: |
          sudo apt-get update -y >/dev/null 2>&1
          sudo apt-get install -y python3 gettext >/dev/null 2>&1
          python3 Zinsgrabber.py
          git config user.name "GeorgGoldbach"
          git config user.email "87702150+GeorgGoldbach@users.noreply.github.com"
          git add .
          git commit --quiet --allow-empty -m "Updated: `date +'%Y-%m-%d %H:%M'` (GitHub Actions)"
          git push
